<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class NftDataSeeder extends Seeder
{
    public function run()
    {
        // Заполнение таблицы nfts
        $nftsData = [
            // 1
            [
                'title' => 'Цифровой Давид',
                'description' => 'Известную в Италии и России работу "Цифровой Давид". Эскиз создали команда Ассоциации художников Граффити Россия.',
                'image' => '/img/nft/1/nft1.png',
                'previous_price' => '167.8',
                'price' => '1167.8',
                'tags' => 'nft,art,space,generative',
                'user_id' => 2,
                'category_id' => 1,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Современный художник',
                'description' => 'Эту работу можно купить в комплекте с NFT-токеном в рамках совместного с художниками проекта «Отражение».',
                'image' => '/img/nft/1/nft2.png',
                'previous_price' => '167.8',
                'price' => '120.5',
                'previous_price' => '167.8',
                'tags' => 'nft,art,digital,abstract',
                'user_id' => 3,
                'category_id' => 1,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Неоновые джунгли',
                'description' => 'Фантастический пейзаж, где природа переплетается с технологией. Яркие неоновые краски.',
                'image' => '/img/nft/1/nft3.png',
                'previous_price' => '1167.8',
                'price' => '1245.3',
                'tags' => 'nft,art,neon,fantasy',
                'user_id' => 2,
                'category_id' => 1,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Цифровой Давид',
                'description' => 'Известную в Италии и России работу "Цифровой Давид". Эскиз создали команда Ассоциации художников Граффити Россия.',
                'image' => '/img/nft/1/nft1.png',
                'previous_price' => '167.8',
                'price' => '1167.8',
                'tags' => 'nft,art,space,generative',
                'user_id' => 2,
                'category_id' => 1,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            // 2
            [
                'title' => 'The Electric Playmaker',
                'description' => 'Это эксклюзивное цифровое произведение искусства запечатлело квинтэссенцию футуристического спорта.',
                'image' => '/img/nft/1/nft4.png',
                'previous_price' => '1167.8',
                'price' => '2345.0',
                'tags' => 'nft,sports,basketball,championship',
                'user_id' => 3,
                'category_id' => 2,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Кибер-Слэм №5',
                'description' => 'Футуристический робот в черно-белой броне зависает в воздухе для мощного слэм-данка.',
                'image' => '/img/nft/1/nft5.png',
                'previous_price' => '1167.8',
                'price' => '310.2',
                'tags' => 'nft,sports,athletics,record',
                'user_id' => 2,
                'category_id' => 2,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Сиреневый Атлет',
                'description' => 'Уникальный цифровой актив, изображающий могучую, но минималистичную фигуру в сиреневых тонах.',
                'image' => '/img/nft/1/nft6.png',
                'previous_price' => '1367.8',
                'price' => '1580.5',
                'tags' => 'nft,sports,football,goal',
                'user_id' => 3,
                'category_id' => 2,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Кибер-Слэм №5',
                'description' => 'Футуристический робот в черно-белой броне зависает в воздухе для мощного слэм-данка.',
                'image' => '/img/nft/1/nft5.png',
                'previous_price' => '1167.8',
                'price' => '310.2',
                'tags' => 'nft,sports,athletics,record',
                'user_id' => 2,
                'category_id' => 2,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],

            // 3

            [
                'title' => 'Древний амулет: Знак дракона',
                'description' => 'Реплика мистического амулета из легенд Востока. 3D-модель с эффектом старения и скрытыми символами.',
                'image' => '/img/nft/1/nft7.png',
                'previous_price' => '467.8',
                'price' => '998.5',
                'tags' => 'nft,collectible,myth,artifact',
                'user_id' => 2,
                'category_id' => 3,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Талисман безопасности',
                'description' => 'талисманом программы НАСА по повышению безопасности полетов.',
                'image' => '/img/nft/1/nft8.png',
                'previous_price' => '11167.8',
                'price' => '12275.3',
                'tags' => 'nft,collectible,coin,history',
                'user_id' => 3,
                'category_id' => 3,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Серебряный Снупи',
                'description' => 'Астронавты вручают сотрудникам и подрядчикам НАСА престижную награду Серебряный Снупи.',
                'image' => '/img/nft/1/nft9.png',
                'previous_price' => '22167.8',
                'price' => '1188.7',
                'tags' => 'nft,collectible,map,treasure',
                'user_id' => 2,
                'category_id' => 3,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Древний амулет: Знак дракона',
                'description' => 'Реплика мистического амулета из легенд Востока. 3D-модель с эффектом старения и скрытыми символами.',
                'image' => '/img/nft/1/nft7.png',
                'previous_price' => '467.8',
                'price' => '998.5',
                'tags' => 'nft,collectible,myth,artifact',
                'user_id' => 2,
                'category_id' => 3,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            //4

            [
                'title' => 'Закат над Гималаями',
                'description' => 'Фотопанорама высочайших вершин мира в золотых лучах заката. Разрешение 8K, детализация до мельчайших трещин на скалах.',
                'image' => '/img/nft/1/nft10.png',
                'previous_price' => '167.8',
                'price' => '175.2',
                'tags' => 'nft,photography,nature,himalayas',
                'user_id' => 3,
                'category_id' => 4,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Туман над озёром',
                'description' => 'Атмосферная фотография утреннего тумана, окутывающего спокойное озеро. Высокая детализация текстур.',
                'image' => '/img/nft/1/nft11.png',
                'previous_price' => '222167.8',
                'price' => '333360.4',
                'tags' => 'nft,photography,nature,lake',
                'user_id' => 2,
                'category_id' => 4,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Город в дождь: Неоновые огни',
                'description' => 'Ночной снимок улицы в дожде, где отражения неоновых вывесок создают виртуальную атмосферу.',
                'image' => '/img/nft/1/nft12.png',
                'previous_price' => '21167.8',
                'price' => '1285.7',
                'tags' => 'nft,photography,urban,rain',
                'user_id' => 3,
                'category_id' => 4,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],

            [
                'title' => 'Туман над озёром',
                'description' => 'Атмосферная фотография утреннего тумана, окутывающего спокойное озеро. Высокая детализация текстур.',
                'image' => '/img/nft/1/nft11.png',
                'previous_price' => '222167.8',
                'price' => '333360.4',
                'tags' => 'nft,photography,nature,lake',
                'user_id' => 2,
                'category_id' => 4,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            // 5
            [
                'title' => 'meta.city',
                'description' => 'Короткий домен для проектов в метавселенных. Идеален для виртуальных городов, игровых платформ и NFT-маркетплейсов.',
                'image' => '/img/nft/1/nft13.png',
                'previous_price' => '4227.8',
                'price' => '41231.0',
                'tags' => 'nft,domain,metaverse,web3',
                'user_id' => 2,
                'category_id' => 5,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'art.zone',
                'description' => 'Домен для цифровых художников и галерей. Короткий и запоминающийся.',
                'image' => '/img/nft/1/nft14.png',
                'previous_price' => '33167.8',
                'price' => '35550.5',
                'tags' => 'nft,domain,art,nft',
                'user_id' => 3,
                'category_id' => 5,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'game.hub',
                'description' => 'Идеальный домен для игрового сообщества или хаба блокчейн-игр.',
                'image' => '/img/nft/1/nft15.png',
                'previous_price' => '13267.8',
                'price' => '24250.7',
                'tags' => 'nft,domain,game,web3',
                'user_id' => 2,
                'category_id' => 5,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],


            [
                'title' => 'meta.city',
                'description' => 'Короткий домен для проектов в метавселенных. Идеален для виртуальных городов, игровых платформ и NFT-маркетплейсов.',
                'image' => '/img/nft/1/nft13.png',
                'previous_price' => '4227.8',
                'price' => '41231.0',
                'tags' => 'nft,domain,metaverse,web3',
                'user_id' => 2,
                'category_id' => 5,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            //6

            [
                'title' => 'Кибер‑куртка: Неоновый драйв',
                'description' => 'Цифровая куртка с динамической подсветкой и эффектом «текучего металла». Подходит для аватаров в метавселенных.',
                'image' => '/img/nft/1/nft16.png',
                'previous_price' => '167.8',
                'price' => '120.3',
                'tags' => 'nft,fashion,cyberpunk,avatar',
                'user_id' => 3,
                'category_id' => 6,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Плащ иллюзий',
                'description' => 'Виртуальный плащ с эффектом хамелеона: меняет цвет и текстуру в зависимости от окружения аватара.',
                'image' => '/img/nft/1/nft17.png',
                'previous_price' => '2167.8',
                'price' => '595.7',
                'tags' => 'nft,fashion,avatar,magic',
                'user_id' => 2,
                'category_id' => 6,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Спортивные кроссовки: Гравитация',
                'description' => 'Цифровые кроссовки с анимацией светящихся подошв и эффектом невесомости при ходьбе аватара.',
                'image' => '/img/nft/1/nft18.png',
                'previous_price' => '3144.8',
                'price' => '3211.4',
                'tags' => 'nft,fashion,sports,avatar',
                'user_id' => 3,
                'category_id' => 6,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Плащ иллюзий',
                'description' => 'Виртуальный плащ с эффектом хамелеона: меняет цвет и текстуру в зависимости от окружения аватара.',
                'image' => '/img/nft/1/nft17.png',
                'previous_price' => '2167.8',
                'price' => '595.7',
                'tags' => 'nft,fashion,avatar,magic',
                'user_id' => 2,
                'category_id' => 6,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            // 7

            [
                'title' => 'Эпический меч: Пламя дракона',
                'description' => 'Оружие с анимацией огненного лезвия и уникальным эффектом взрыва при ударе. Подходит для RPG-игр.',
                'image' => '/img/nft/1/nft19.png',
                'previous_price' => '4245.8',
                'price' => '5242.0',
                'tags' => 'nft,game,weapon,dragon,sword',
                'user_id' => 2,
                'category_id' => 7,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Персонаж: Ледяной маг',
                'description' => 'Игровой персонаж с уникальными способностями заморозки и визуальными эффектами льда.',
                'image' => '/img/nft/1/nft20.png',
                'previous_price' => '9657.8',
                'price' => '7764.0',
                'tags' => 'nft,game,character,mage,fantasy',
                'user_id' => 3,
                'category_id' => 7,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Земельный участок: Вулканическая равнина',
                'description' => 'Виртуальная земля в игровом мире с уникальными ресурсами и возможностью строительства.',
                'image' => '/img/nft/1/nft21.png',
                'previous_price' => '543.8',
                'price' => '250.7',
                'tags' => 'nft,game,land,real estate,volcano',
                'user_id' => 2,
                'category_id' => 7,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],

            [
                'title' => 'Персонаж: Ледяной маг',
                'description' => 'Игровой персонаж с уникальными способностями заморозки и визуальными эффектами льда.',
                'image' => '/img/nft/1/nft20.png',
                'previous_price' => '9657.8',
                'price' => '7764.0',
                'tags' => 'nft,game,character,mage,fantasy',
                'user_id' => 3,
                'category_id' => 7,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            // 8
            [
                'title' => 'Трек: Космическая симфония',
                'description' => 'Эксклюзивный аудиотрек в стиле синтез-вейв с визуализацией галактических паттернов.',
                'image' => '/img/nft/1/nft22.png',
                'previous_price' => '1242.8',
                'price' => '1553.7',
                'tags' => 'nft,music,electronic,synthwave,cosmic',
                'user_id' => 3,
                'category_id' => 8,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Альбом: Ночь в городе',
                'description' => 'Коллекция из 8 треков в жанре лоу-фай. Включает анимированные обложки и эксклюзивные сэмплы.',
                'image' => '/img/nft/1/nft23.png',
                'previous_price' => '13367.8',
                'price' => '18220.3',
                'tags' => 'nft,music,album,lofi,city',
                'user_id' => 2,
                'category_id' => 8,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Сэмпл: Звук дождя в лесу',
                'description' => 'Высококачественный аудиосэмпл с записью реального лесного дождя. Используется в амбиент-музыке.',
                'image' => '/img/nft/1/nft24.png',
                'previous_price' => '33367.8',
                'price' => '33335.4',
                'tags' => 'nft,music,sample,ambient,rain',
                'user_id' => 3,
                'category_id' => 8,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Трек: Космическая симфония',
                'description' => 'Эксклюзивный аудиотрек в стиле синтез-вейв с визуализацией галактических паттернов.',
                'image' => '/img/nft/1/nft22.png',
                'previous_price' => '1242.8',
                'price' => '1553.7',
                'tags' => 'nft,music,electronic,synthwave,cosmic',
                'user_id' => 3,
                'category_id' => 8,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            // 9

            [
                'title' => 'Виртуальный отель: Звёздный бриз',
                'description' => 'Премиум-здание в метавселенной с возможностью аренды и проведения мероприятий.',
                'image' => '/img/nft/1/nft25.png',
                'previous_price' => '634.8',
                'price' => '744.0',
                'tags' => 'nft,metaverse,real estate,hotel,premium',
                'user_id' => 2,
                'category_id' => 9,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Офис в облаках',
                'description' => 'Пространство для виртуального бизнеса. Включает конференц-залы и зоны отдыха.',
                'image' => '/img/nft/1/nft26.png',
                'previous_price' => '532.8',
                'price' => '2423.5',
                'tags' => 'nft,metaverse,real estate,office,cloud',
                'user_id' => 3,
                'category_id' => 9,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Жилой комплекс: Лунная бухта',
                'description' => 'Апартаменты на виртуальной Луне. Включает 3D-модели и анимированные панорамы.',
                'image' => '/img/nft/1/nft27.png',
                'previous_price' => '8564.8',
                'price' => '6543.7',
                'tags' => 'nft,metaverse,real estate,residential,lunar',
                'user_id' => 2,
                'category_id' => 9,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Офис в облаках',
                'description' => 'Пространство для виртуального бизнеса. Включает конференц-залы и зоны отдыха.',
                'image' => '/img/nft/1/nft26.png',
                'previous_price' => '532.8',
                'price' => '2423.5',
                'tags' => 'nft,metaverse,real estate,office,cloud',
                'user_id' => 3,
                'category_id' => 9,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            // 10
            [
                'title' => 'Портрет: Цифровое сознание',
                'description' => 'Искусственный портрет, созданный нейросетью. Эволюционирует при каждом просмотре.',
                'image' => '/img/nft/1/nft28.png',
                'previous_price' => '643.8',
                'price' => '234.5',
                'tags' => 'nft,ai,art,portrait,evolving',
                'user_id' => 3,
                'category_id' => 10,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Мир: Генеративная галактика',
                'description' => 'Виртуальная галактика, создаваемая ИИ в реальном времени. Уникальные звёзды и планеты при каждом запуске.',
                'image' => '/img/nft/1/nft29.png',
                'previous_price' => '634.8',
                'price' => '754.8',
                'tags' => 'nft,ai,art,galaxy,generative',
                'user_id' => 2,
                'category_id' => 10,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Абстракция: Код сознания',
                'description' => 'Арт, визуализирующий нейронные связи. Цвета и формы зависят от настроения владельца.',
                'image' => '/img/nft/1/nft30.png',
                'previous_price' => '2346.8',
                'price' => '6432.2',
                'tags' => 'nft,ai,art,abstract,neural',
                'user_id' => 3,
                'category_id' => 10,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
            [
                'title' => 'Мир: Генеративная галактика',
                'description' => 'Виртуальная галактика, создаваемая ИИ в реальном времени. Уникальные звёзды и планеты при каждом запуске.',
                'image' => '/img/nft/1/nft29.png',
                'previous_price' => '634.8',
                'price' => '754.8',
                'tags' => 'nft,ai,art,galaxy,generative',
                'user_id' => 2,
                'category_id' => 10,
                'status' => 'relevant',
                'created_at' => Carbon::now()->second(rand(0, 59)),
                'updated_at' => Carbon::now()->second(rand(0, 59)),
            ],
        ];

        // Заполнение таблицы categories
        $categoryData = [
            [
                'id' => 1,
                'img' => '/img/nft/category/category1.png',
                'imgFon' => '/img/nft/category/categoryFon1.png',
                'name' => 'NFT Art',
                'description' => 'Уникальные цифровые произведения: от ручной графики до генеративного искусства. Включает анимированные работы, 3D‑модели и экспериментальные медиа.'
            ],
            [
                'id' => 2,
                'img' => '/img/nft/category/category2.png',
                'imgFon' => '/img/nft/category/categoryFon2.png',
                'name' => 'Sports Memorabilia',
                'description' => 'Цифровые артефакты спорта: культовые моменты матчей, виртуальные карточки игроков, коллекционная экипировка и трофеи.'
            ],
            [
                'id' => 3,
                'img' => '/img/nft/category/category3.png',
                'imgFon' => '/img/nft/category/categoryFon3.png',
                'name' => 'Collectibles',
                'description' => 'Лимитированные цифровые предметы: фигурки, редкие артефакты, тематические серии и объекты для метавселенных.'
            ],
            [
                'id' => 4,
                'img' => '/img/nft/category/category4.png',
                'imgFon' => '/img/nft/category/categoryFon4.png',
                'name' => 'Digital Photography',
                'description' => 'Эксклюзивные фотоработы: арт‑съёмка, документальные серии, ограниченные издания в высоком разрешении.'
            ],
            [
                'id' => 5,
                'img' => '/img/nft/category/category5.png',
                'imgFon' => '/img/nft/category/categoryFon5.png',
                'name' => 'Domain Names',
                'description' => 'Цифровые домены для веб‑проектов и метавселенных: короткие имена, премиум‑зоны, брендовые адреса.'
            ],
            [
                'id' => 6,
                'img' => '/img/nft/category/category6.png',
                'imgFon' => '/img/nft/category/categoryFon6.png',
                'name' => 'Virtual Fashion',
                'description' => 'Цифровая одежда и аксессуары для аватаров: лимитированные коллекции, коллабы с дизайнерами, скины для игр.'
            ],
            [
                'id' => 7,
                'img' => '/img/nft/category/category7.png',
                'imgFon' => '/img/nft/category/categoryFon7.png',
                'name' => 'Game Assets',
                'description' => 'Предметы для игр: оружие, персонажи, земельные участки, пропуска и уникальные способности в блокчейн‑проектах.'
            ],
            [
                'id' => 8,
                'img' => '/img/nft/category/category8.png',
                'imgFon' => '/img/nft/category/categoryFon8.png',
                'name' => 'Music & Audio',
                'description' => 'Эксклюзивные треки, сэмплы, альбомы и звуковые эффекты в NFT‑формате. Включает анимированные обложки и визуализации.'
            ],
            [
                'id' => 9,
                'img' => '/img/nft/category/category9.png',
                'imgFon' => '/img/nft/category/categoryFon9.png',
                'name' => 'Metaverse Real Estate',
                'description' => 'Виртуальные участки, здания и интерьеры для метавселенных: инвестиционные лоты, выставочные пространства, игровые зоны.'
            ],
            [
                'id' => 10,
                'img' => '/img/nft/category/category10.png',
                'imgFon' => '/img/nft/category/categoryFon10.png',
                'name' => 'AI Generations',
                'description' => 'Арт, созданный нейросетями: от абстрактных композиций до фотореалистичных миров. Включает интерактивные и эволюционирующие NFT.'
            ]
        ];

        // Вставка данных
        DB::table('categories')->insert($categoryData);
        DB::table('nfts')->insert($nftsData);
    }
}
